version: '3.1'

services:
  joomla:
    build:
      context: ./docker
      args:
        #VERSION: 3.9.22-php5-apache
        VERSION: 3-php5.6-apache
    ports:
      - 80:80
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_PASSWORD: root
    volumes:
      - ./plg_system_joomshoppingerip:/usr/local/src/plg_system_joomshoppingerip
    #   - ./plg_system_joomshoppingerip/libraries:/var/www/html/plugins/system/joomshoppingerip/libraries
    #   - ./plg_system_joomshoppingerip/joomshoppingerip.xml:/var/www/html/plugins/system/joomshoppingerip/joomshoppingerip.xml
    #   - ./plg_system_joomshoppingerip/joomshoppingerip.php:/var/www/html/plugins/system/joomshoppingerip/joomshoppingerip.php
    #   - ./plg_system_joomshoppingerip/install_uninstall.php:/var/www/html/plugins/system/joomshoppingerip/install_uninstall.php
    #   - ./plg_system_joomshoppingerip/index.html:/var/www/html/plugins/system/joomshoppingerip/index.html
    #   - ./plg_system_joomshoppingerip/language/ru-RU/ru-RU.plg_system_joomshoppingerip.ini:/var/www/html/administrator/language/ru-RU/ru-RU.plg_system_joomshoppingerip.ini
    #   - ./plg_system_joomshoppingerip/language/ru-RU/ru-RU.plg_system_joomshoppingerip.sys.ini:/var/www/html/administrator/language/ru-RU/ru-RU.plg_system_joomshoppingerip.sys.ini
    #   - ./plg_system_joomshoppingerip/language/en-GB/en-GB.plg_system_joomshoppingerip.ini:/var/www/html/administrator/language/en-GB/en-GB.plg_system_joomshoppingerip.ini
    #   - ./plg_system_joomshoppingerip/language/en-GB/en-GB.plg_system_joomshoppingerip.sys.ini:/var/www/html/administrator/language/en-GB/en-GB.plg_system_joomshoppingerip.sys.ini
    #   - ./plg_system_joomshoppingerip/libraries/pm_erip:/var/www/html/components/com_jshopping/payments/pm_erip

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
